### PR TITLE
Fixed Priestcheck and added a package that can be used to store commands that directly message chat 

### PR DESCRIPTION
**Pull request by epicseven-cup**
Added help command need help with line break
added none command matched testing when invalid command is pressed
added another package to store comments that directly message in the chat
Fixed Priestchecker went the old fascination way that if he's there he will talk in chat. Twitch's live user #join and #part is stored in catch and release every few seconds so it's not very accurate.

### CODE REVIEW

**Comment by epicseven-cup** [comment]
Not very sure why is the comment having conflicts with the file I will let jesse check with that

**Comment by jayceguo** [comment]
Wow, still up, bro

**Comment by jayceguo** [comment]
Might have a conflict with my branch because I refactor the whole project directory, I would help you solve the conflict if my pr got merged. Sry for the inconvenience.

**Comment by epicseven-cup** [comment]
ah I see all good no worries

**Pull request closed without merging**
